export const productsList =[
    {   image:'https://www.google.com/url?sa=i&url=https%3A%2F%2Fohbeautybar.ru%2Fochisshenie%2F1521-jon-bird-s-nest-cleansing-oil.html&psig=AOvVaw2zYjIQivYvQu-X9QDL10Vp&ust=1692565383230000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCJCUz8XP6YADFQAAAAAdAAAAABAE',
        description:'Антивозрастное гидрофильное масло с экстрактом ласточкиного гнезда J:ON Birds Nest Cleansing Oil',
        price:'1300p.',
        brand:'J:ON',
        new:true,
        sale:false,
        bestseller:true,
        matureSkin:true,
        sensitiveSkin:false,
        oilySkin:false,
        drySkin:false,
        problemSkin:false,
        forBody:false,

    },
    {image:'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.japandostavka.ru%2Fid%2Fmaslo-dlya-lica-ochischauschee-na-osnove-499055.html&psig=AOvVaw3vL12RoqEmtuCi5uc_twmv&ust=1692565492104000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCNi1nfnP6YADFQAAAAAdAAAAABAE',
    description:'Масло для лица очищающее на основе цветочных экстрактов Deoproce Cleansing Oil Floral Calming',
    price:'950p.',
    brand:'Deoproce',
    new:false,
    sale:true,
    bestseller:true,
    matureSkin:true,
    sensitiveSkin:false,
    oilySkin:false,
    drySkin:true,
    problemSkin:false,
    forBody:false,

},
{   image:'https://cosmasi.ru/image/cache/data/Deoproce/Cleansing%20Oil%20Total%20Energy%20200ml%20Deoproce-500x500.jpg',
description:'Масло очищающее для лица оливковое Deoproce Cleansing Oil Total Energy',
price:'950p.',
brand:'Deoproce',
sale:false,
new:true,
bestseller:true,
matureSkin:true,
sensitiveSkin:false,
oilySkin:false,
drySkin:false,
problemSkin:false,
forBody:false,

},
{   image:'',
description:'THE SAEM SNAIL ESSENTIAL EX HYDRA RADIANCE MASK Несмываемая пузырьковая маска с муцином улитки',
price:'1520p.',
brand:'THE SAEM',
new:false,
sale:true,
bestseller:true,
matureSkin:false,
sensitiveSkin:true,
oilySkin:false,
drySkin:false,
problemSkin:false,
forBody:false,

},
{   image:'https://cosmasi.ru/image/cache/data/SAEM2/The-Saem-cell-renew-bio-micro-peel-intense-gel-500x500.jpg',
description:'THE SAEM CELL RENEW BIO MICRO PEEL INTENSE GEL Интенсивный пилинг-гель с растительными стволовыми клетками',
price:'900p.',
brand:'THE SAEM',
sale:false,
new:true,
bestseller:false,
matureSkin:false,
sensitiveSkin:false,
oilySkin:false,
drySkin:false,
problemSkin:false,
forBody:false,

},
{   image:'https://cosmasi.ru/image/cache/data/GraceDay/Grace-Day-premium-retinol-x9-perfect-cream--500x500.jpg',
description:'GRACE DAY PREMIUM RETINOL X9 PERFECT CREAM Антивозрастной крем с ретинолом',
price:'670p.',
brand:'GRACE DAY',
new:false,
sale:true,
bestseller:false,
matureSkin:true,
sensitiveSkin:false,
oilySkin:false,
drySkin:true,
problemSkin:false,
forBody:false,

},
{   image:'https://cosmasi.ru/image/cache/data/Eyenlip-2/Eyenlip-black-snail-neck-cream-8708-500x500.jpg',
description:'EYENLIP BLACK SNAIL NECK CREAM Крем для шеи антивозрастной',
price:'560p.',
brand:'EYENLIP',
new:true,
sale:false,
bestseller:true,
matureSkin:true,
sensitiveSkin:false,
oilySkin:false,
drySkin:false,
problemSkin:false,
forBody:false,
},
{   image:'https://cosmasi.ru/image/cache/data/48700f1519-500x500.jpg',
description:'Эмульсия питательная с экстрактом новозеландского льна The Saem Urban Eco Harakeke Emulsion',
price:'560p.',
brand:'THE SAEM',
new:true,
sale:false,
bestseller:true,
matureSkin:true,
sensitiveSkin:true,
oilySkin:false,
drySkin:false,
problemSkin:false,
forBody:false,
},

{   image:'https://cosmasi.ru/image/cache/data/Meishoku/Meishoku_aha_bha_hot_cleansing_gel_cream_7990-500x500.jpg',
description:'Разогревающий и очищающий крем-гель с aha и bha кислотами Meishoku Aha & Bha Hot Cleansing Gel Cream',
price:'1410p.',
brand:'Meishoku',
new:false,
sale:false,
bestseller:true,
matureSkin:true,
sensitiveSkin:true,
oilySkin:false,
drySkin:false,
problemSkin:true,
forBody:false,
},

]
